[features]
seeds = false
skip-lint = false
[programs.localnet]
tokenfaucet = "8omPPdRdNGtbeyTHn7zGhu7L3sXj2m2oesMrxE4fpTRh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
